name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pytest
        python -m pip install -e .

    - name: Install CIF
      run: |
        curl -sSfL -o cif.tar.xz https://github.com/17451k/cif/releases/download/2019-09-02/cif-20190902-linux-x64.tar.xz
        tar xf cif.tar.xz

    - name: Test with pytest
      run: |
        PATH=$(pwd)/cif/bin:$PATH pytest
