name: Tinyconfig

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11" 

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz gcc-multilib make

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade pytest
        python -m pip install -e .

    - name: Download CIF
      run: |
        curl -sSfL -o cif.tar.xz https://github.com/ldv-klever/cif/releases/download/v1.2/linux-x86_64-cif-1.2.tar.xz

    - name: Install CIF
      run: |
        tar xf cif.tar.xz

    - name: Clone Linux kernel
      run: |
        git clone --depth 1 https://github.com/torvalds/linux

    - name: Configure Linux kernel
      run: |
        cd linux
        make tinyconfig

    - name: Build Linux kernel with Clade
      run: |
        cd linux
        PATH=$GITHUB_WORKSPACE/cif/bin:$PATH clade -p linux_kernel -e Callgraph -e Macros make -j$(nproc)
        zip -r clade-linux-kernel-tinyconfig.zip clade

    - uses: actions/upload-artifact@v3
      with:
        name: clade-linux-kernel-tinyconfig
        path: linux/clade-linux-kernel-tinyconfig.zip

